# FBA - Python Test 23-24

* You have 2 hours to finish this test.
* Please enter your answers into the spaces provided.
* We recommend that you show comments in your code, to evidence your working if possible (comments may earn some credits even if your script code is not 100% correct).
* In this test you will not be marked on elegance or efficiency, but rather getting the correct result in the instructed manner.
* Partial answers can still gain some marks, so please move onto the next question if you get stuck.
* As a guideline, section 6 is roughly halfway through the test.

### Your Name
Please print out your full name and student ID in the box below

In [1]:
#print out your full name here
print("")#自己写一下，我不知道这俩
#print out your student ID here
print("")#自己写一下，我不知道这俩

## Section 1 - Variables, Types & Casting

### Q1.1: Variable assignment (1 mark)

Assign your own student ID to a variable `ID` using the `input` function. 


In [1]:
#enter your answer here
ID = input("Enter your own student ID:")
#assign your own student ID as an integer to a variable **ID**
print(int(ID))


Enter your own student ID:123456
123456


### Q1.2: Data Types & Casting  (3 marks)

- Assign your height as a float to a variable `height` using the input function.
- Assign your weight as a float to a variable `weight` using the input function.
- Assign your name as a string to a variable `name` using the input function.
- Calculate your BMI using the values of `height` and `weight`, and assign it to a new variable `bmi`.
- Print your name and your BMI together in the following format: "[Your Name]'s BMI equals [Your BMI]", e.g., "John's BMI is 24.7".

Note:  
BMI is calculated as **weight / (height * height)**. </b>  
You don't need to provide your real height and weight. You may create some fictional numbers.

In [3]:
#enter your answer here
height = float(input("Enter your height in meters:"))
weight = float(input("Enter your weight in kilograms:"))
name = input("Enter your name:")
bmi = weight / (height * height)
print(name,"'s BMI equals ",bmi)

Enter your height in meters:1.8
Enter your weight in kilograms:80
Enter your name:john
john 's BMI equals  24.691358024691358


## Section 2 - Loops & Conditionals

In this section, you are required to write a program that prints a pattern of caret (`^`) in the shape of an isosceles trapezoid ("等腰梯形" in Chinese). The isosceles trapezoid has the following dimensions:

- Lower Base: 8
- Upper Base: 4
- Height: 3

#### Example Output

Your program should produce patterns similar to the following:  
&ensp;&nbsp; ^^^^  
&nbsp; ^^^^^^  
^^^^^^^^  

**Note**: The first line of `^` should begin with two spaces, the second line of `^` should start with one space, and the third line of `^` starts with no space.

Please complete this task with the following functions:

### Q2.1: Using a `for loop` and the` range()` function - Option 1 (3 marks)

In [6]:
#enter your answer here
for i in range(0,3):
    print(" "*(2-i)+"^"*(4+i*2))

  ^^^^
 ^^^^^^
^^^^^^^^


### Q2.2: Using a `while` loop - Option 2 (3 marks)

This time we want to use a `while loop` with a `counter`. The condition of your while loop should depend on a variable you create to count where you are in the loop.

In [9]:
#enter your answer here
i = 0
while i < 3:
    print(" "*(2-i)+"^"*(4+i*2))
    i+=1

  ^^^^
 ^^^^^^
^^^^^^^^


### Q2.3: Using a `while True` loop - Option 3 (3 marks)

This time we want to use a `counter` and `while True` loop. You must exit the loop using  the `continue` or `break` statement (n.b. only one of these two commands will do what you want), and any other commands that you think useful.

In [10]:
#enter your answer here
i = 0
while True:
    print(" "*(2-i)+"^"*(4+i*2))
    if i<2:
        i+=1
        continue
    else:
        break

  ^^^^
 ^^^^^^
^^^^^^^^


# Section 3 - If statements

### Q3.1: if and else statements (3 marks)

Given the a variable `password` which takes password settings from the users, write a program to check if the password set by the user meets the security requirements:

- The length of the password must be longer than 5 characters. If it is shorter than or equal to 5 characters, print: **"The password must be longer than 5 characters."**
- If the password meets the secuirty requirements, i.e., the length of the password is longer than 6 and does not start with "12345" or "qwert", print: **"You have successfully set up your password".**

Remember that you have to use **if** and **else** in this question.

In [18]:
password = input()    # You can change the value of password to cover the different cases and test your code
#enter your answer here
import re
if len(password) <= 5:
    print("The password must be longer than 5 characters.")
elif re.match(r"12345",password) == None or re.match(r"qwerty",password) == None:
    print("You have successfully set up your password.")
else:
    print("The password does not start with 12345 or qwert.")

qwerty
You have successfully set up your password.


### Q3.2: Using if, elif and else (3 marks)
Add an extra condition in the program above such that it will check if the password is on a list of common or easily guessable passords. 

The passwords in the list of common passwords include: `"letmein", "password", "12345", "qwerty"`

If the password is in the list, print: "Your password is too simple."

In [1]:
password = input()    # You can change the value of password to cover the different cases and test your code

#enter your answer here
import re
if len(password) <= 5:
    print("The password must be longer than 5 characters.")
elif re.search("letmein",password) != None or re.search("password",password) != None or re.search("12345",password) != None or re.search("qwerty",password) != None:
    print("Your password is too simple.")
else:
    print("You have successfully set up your password.")

letmein
Your password is too simple.


### Q3.3: Nested conditionals (5 marks)
Finally, please use `nested if` statements to specify the security requirements for password:
    
- If the password shorter than or equal to 5 characters, 
    - Print: **"The password must be longer than 5 characters."**
- If the password longer than 5 characters: 
    - And if it is not a combination of characters and numbers, print: **"Your password should be a combination of characters and numbers."**
    - And if it is a combination of characters and numbers, print: **"You have successfully set up your password".** 
    

In [6]:
password = input()    # You can change the value of password to cover the different cases and test your code
#enter your answer here
pattern = r"^(?=.*[a-zA-Z])(?=.*\d).+$"
if len(password) <= 5:
    print("The password must be longer than 5 characters.")
elif re.match(pattern, password):
    print("You have successfully set up your password.")
else:
    print("Your password should be a combination of characters and numbers.")

123456
Your password should be a combination of characters and numbers.


# Section 4 - Data Structures

### Q4.1: List creation (3 marks)

Create a 2 level list `ls` from a given string `s` = "apple,banana,cherry,durian".The first list of `ls` should contain the first two items of `s` and the second list should contain the last two items of `s`. Print out the final list.

In [7]:
s = "apple,banana,cherry,durian" #generate ls based on s
#enter your answer here
items = s.split(',')
ls = [items[:2], items[2:]]
print(ls)

[['apple', 'banana'], ['cherry', 'durian']]


### Q4.2: List modification with index (2 marks)

Given a new list `list_new` which contains two fruits `["pear", "lemon", "grape"]`, update the original list `ls` and change the first list of `ls` to be the first two items of `list_new` (i.e., replace ['apple', 'banana'] by ["pear", "lemon"]), and update the last element of the second list of `ls` to 'pear' to the second item of `list_new` (i.e., replace "durian" by "grape"). The updated `list_new` should be `[["pear", "lemon"], ['cherry', 'grape']]`, and then print it out. 

In [8]:
ls = [['apple', 'banana'], ['cherry', 'durian']]
list_new = ["pear", "lemon", "grape"]

#enter your answer here
ls[0] = list_new[:2]  
ls[1][-1] = list_new[2] 

print(ls)  # the final output should be [['pear', 'lemon'], ['cherry', 'grape']]

[['pear', 'lemon'], ['cherry', 'grape']]


### Q4.3: Insert values to list (2 marks)

Based on the updated list `[[ 'pear', 'lemon'], ['cherry', 'grape']]`, insert a new list `['apple', 'banana']` between the original `[ 'pear', 'lemon']` and `['cherry', 'grape']`, so that the final list becomes `[[ 'pear', 'lemon'], ['apple', 'banana'], ['cherry', 'grape']]`.

In [10]:
# Use the variable below to compelete this task if you fail to create new_array in the previous question
# ls = [['pear', 'lemon'], ['cherry', 'grape']] 

#enter your answer here
ls = [['pear', 'lemon'], ['cherry', 'grape']]
ls.insert(1, ['apple', 'banana'])

print(ls) # the final output should be [['pear', 'lemon'], ['apple', 'banana'], ['cherry', 'grape']]

[['pear', 'lemon'], ['apple', 'banana'], ['cherry', 'grape']]


### Q4.4: Dictionary creation (3 marks)

Given two lists `names` and `birthdays`, create a dictionary `student_info` where the keys are the names from the `names` list and the values are the corresponding birthdays from the `birthdays` list. The final dictionary should look like this:

{
    "John": "01/01/2000",
    "Jane": "02/14/2001",
    "Jim": "03/15/1999",
    "Joan": "04/10/1998"
}


In [11]:
names = ["John", "Jane", "Jim", "Joan"]
birthdays = ["01/01/2000", "02/14/2001", "03/15/1999", "04/10/1998"]

#enter your answer here
student_info = dict(zip(names, birthdays))
print(student_info)

{'John': '01/01/2000', 'Jane': '02/14/2001', 'Jim': '03/15/1999', 'Joan': '04/10/1998'}


### Q4.5: Iterate through dictionary  (5 marks)

Create a new dictionary `student_age` which contains the names and ages of the students in `student_info`. The age should be calculated based on the `current_year` and the birth date stored in `student_info`. 

Note:   
Assume the `current_year` is 2023.  
No need to consider the date of birth when calculating age. You may simply calculate age as the difference between birth year and current year. For example, a person born in 2000 should be 23 in 2023. 

In [12]:
student_info = {'John': '01/01/2000', 'Jane': '02/14/2001', 'Jim': '03/15/1999', 'Joan': '04/10/1998'}

#enter your answer here
current_year = 2023
student_age = {name: current_year - int(birthday.split("/")[-1]) for name, birthday in student_info.items()}

print(student_age) #the output should be {'John': 23, 'Jane': 22, 'Jim': 24, 'Joan': 25}

{'John': 23, 'Jane': 22, 'Jim': 24, 'Joan': 25}


### Q4.6: Generate statistics from dictionary (5 marks)

Based on the ages in `student_age`, find out the maximal, minimal, and average ages of students.

Note: Do not use the `max()` and `min()` function.

In [13]:
student_age = {'John': 23, 'Jane': 22, 'Jim': 24, 'Joan': 25}

# write your code here
max_age = student_age[next(iter(student_age))]  # Initialize max_age with the first value
for age in student_age.values():
    if age > max_age:
        max_age = age

min_age = student_age[next(iter(student_age))]  # Initialize min_age with the first value
for age in student_age.values():
    if age < min_age:
        min_age = age

total_age = sum(student_age.values())
average_age = total_age / len(student_age)

print("Maximal age:", max_age)
print("Minimal age:", min_age)
print("Average age:", average_age)




Maximal age: 25
Minimal age: 22
Average age: 23.5


# Section 5 - Functions

### Q5.1:  Function definition (3 marks)

Define a Python function `calculate_remainder` that calculates and returns the remainder of a division operation. The function should accept two numeric arguments: the `dividend` (the number to be divided) and the `divisor` (the number by which the division is performed).

For example, when the dividend is 7, and the divisor is 5. The `calculate_remainder` function should return the remainder of this division, which is 2.

In [14]:
#enter your answers here
def calculate_remainder(dividend, divisor):
    return dividend % divisor

result = calculate_remainder(7, 5)
print('Remainder:',result)  


Remainder: 2


### Q5.2: Manipulating list with function (4 marks)

Define a function `divisible_by_three` that takes a list of numbers as an argument and returns a new list containing only the numbers that are divisible by 3. The numbers in the new list should be sorted in ascending order. If the input list does not contain any numbers divisible by 3, the function should return an empty list.

In [17]:
numbers = [1, 3, 2, 10, 8, 6, 9, 22, 23, 21, 27] # You may try different values to test your code

#enter your answer here
def divisible_by_three(input_list):
    result_list = [num for num in input_list if num % 3 == 0]
    result_list.sort()
    return result_list
result = divisible_by_three(numbers)
print(result)


[3, 6, 9, 21, 27]


### Q5.3: Check anagrams  (5 marks)

Define a function `is_anagram` that checks whether two given strings are anagrams of each other. Anagrams are words or phrases formed by rearranging the letters of another word or phrase, using all the original letters exactly once. The `is_anagram` function should take two strings as input and return `True` if they are anagrams of each other and `False` otherwise.

##### Examples
Consider the following pairs of strings:

String 1: "listen"  
String 2: "silent"  
These two strings are anagrams of each other because they have the same set of characters rearranged differently. When you rearrange the letters of "listen," you get "silent," and vice versa.

String 1: "triangle"  
String 2: "integral"  
These strings are also anagrams because you can rearrange the letters to form the other word.

String 1: "hello"   
String 2: "world"  
These strings are not anagrams because they have different sets of characters.

**Note**: To sort the characters in strings, you may use the `sorted()` function.

In [18]:
#enter your answers here

def is_anagram(str1, str2):
    str1 = str1.replace(' ', '').lower()
    str2 = str2.replace(' ', '').lower()
    
    sorted_str1 = sorted(str1)
    sorted_str2 = sorted(str2)
    return sorted_str1 == sorted_str2

#test your answer using the following function calls
print(is_anagram("listen", "silent"))  # True
print(is_anagram("triangle", "integral"))  # True
print(is_anagram("hello", "world"))  # False

True
True
False


# Section 6 - Numpy

### Q6.1: Importing Numpy (1 mark)

Import the module Numpy with the usual shortcut name **np**

In [19]:
import numpy as np

### Q6.2: Ndarray creation (1 mark)

Create a 1D numpy array `arr` with integers from -9 to 0.

In [20]:
#enter your answer here
import numpy as np

arr = np.arange(-9, 1)
print(arr)


[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]


### Q6.3: Ndarray shape (1 mark)

Print the shape of `arr`.

In [21]:
#enter your answer here
import numpy as np

arr = np.arange(-9, 1)
print(arr.shape)


(10,)


### Q6.4: Update array shape (1 mark)

Change the shape of `arr` (currently (10,)) to (5,2) and assign it to a new array `new_arr`.

In [22]:
import numpy as np

arr = np.arange(-9, 1)
new_arr = arr.reshape(5, 2)
print(new_arr)

[[-9 -8]
 [-7 -6]
 [-5 -4]
 [-3 -2]
 [-1  0]]


### Q6.5: Transpose array (2 marks)

Transpose `new_arr`,swapping its rows and columns, and assign it to a new array `transpose_array`.

The resulting array should be like this:  
[[-9, -7, -5, -3, -1],  
[-8, -6, -4, -2,  0]]

In [23]:
# Use the variable below to compelete this task if you fail to create new_array in the previous question
# new_arr = np.array([[-9, -8], [-7, -6], [-5, -4], [-3, -2],[-1,  0]]) 
import numpy as np

arr = np.arange(-9, 1)
new_arr = arr.reshape(5, 2)
transpose_array = new_arr.transpose()
print(transpose_array)


[[-9 -7 -5 -3 -1]
 [-8 -6 -4 -2  0]]


### Q6.6: Absolute values in array (2 marks)
Modify the values in `transpose_array` that all the values are replaced with their absolute values. Assign the absolute values to a new array named "absolute_array".

The resulting array should be something like:  
[[9 7 5 3 1]  
 [8 6 4 2 0]]

In [24]:
# Use the variable below to compelete this task if you fail to create new_array in the previous question
# transpose_array = np.array([[-9, -7, -5, -3, -1], [-8, -6, -4, -2,  0]]) 

#enter your answer here
import numpy as np

arr = np.arange(-9, 1)
new_arr = arr.reshape(5, 2)
transpose_array = new_arr.transpose()
absolute_array = np.abs(transpose_array)

# Print the modified array
print(absolute_array)

[[9 7 5 3 1]
 [8 6 4 2 0]]


# Section 7 - Reading a file manually

### Q7.1: Reading the fist column (5 marks)

In the current directory of this Jupyter Notebook, you are given a file `drinks.csv`.

Using the standard Python functions (open(), read(), readlines(), write(), ...), read the **first** and **last** columns, i.e, the country column and the continent column, of the data file.

In [25]:
#enter your answer here
with open('drinks.csv', 'r') as file:
    lines = file.readlines()

first_column = [line.split(',')[0].strip() for line in lines]
last_column = [line.split(',')[-1].strip() for line in lines]

print("First column (country):", first_column)
print("Last column (continent):", last_column)



First column (country): ['country', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia-Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', "Cote d'Ivoire", 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'North Korea', 'DR Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Ir

# Section 8 - Pandas

This time we are going to use Pandas to load the `drinks.csv` file and explore it.

### Q8.1: Loading the CSV file (1 mark)

First of all, import the Pandas module! Using one of Pandas functions, load the data of the CSV file into a dataframe and assign it to a variable **df**

In [26]:
#enter your answer here
import pandas as pd

df = pd.read_csv('drinks.csv')
print(df)


         country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
0                             0.0        AS  
1                             4.9        EU  
2                             0.7        AF  
3          

### Q8.2: Displaying the last 10 lines (1 mark)
Display the last 10 lines of your dataframe

In [28]:
#enter your answer here
df.tail(10)

country  beer_servings  spirit_servings  wine_servings  \
183    Tanzania             36                6              1   
184         USA            249              158             84   
185     Uruguay            115               35            220   
186  Uzbekistan             25              101              8   
187     Vanuatu             21               18             11   
188   Venezuela            333              100              3   
189     Vietnam            111                2              1   
190       Yemen              6                0              0   
191      Zambia             32               19              4   
192    Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
183                           5.7        AF  
184                           8.7       NaN  
185                           6.6        SA  
186                           2.4        AS  
187                           0.9        OC  
188                           7.7        SA  
189                           2.0        AS  
190                           0.1        AS  
191                           2.5        AF  
192                           4.7        AF

### Q8.3: Column creation (4 marks)
Create two new columns `total_alcohol_consumption` and `average_alcohol_consumption` in `df` which is the **total** and **average** of the columns `beer_servings`, `spirit_servings`, `wine_servings`, and `total_litres_of_pure_alcohol`.

In [29]:
#enter your answer here
import pandas as pd

df = pd.read_csv('drinks.csv')

df['total_alcohol_consumption'] = df['beer_servings'] + df['spirit_servings'] + df['wine_servings'] + df['total_litres_of_pure_alcohol']
df['average_alcohol_consumption'] = df['total_alcohol_consumption'] / 4

df.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  total_alcohol_consumption  \
0                           0.0        AS                        0.0   
1                           4.9        EU                      279.9   
2                           0.7        AF                       39.7   
3                          12.4        EU                      707.4   
4                           5.9        AF                      324.9   

   average_alcohol_consumption  
0                        0.000  
1                       69.975  
2                        9.925  
3                      176.850  
4                       81.225

### Q8.4: Replace Values (3 marks)

Replace the abbreviations of `continent` names by their full names, i.e., replace 'AF' by 'Africa', 'AS' by 'Asia', 'EU' by 'Europe', 'OC' by 'Oceania', 'SA' by 'South America' in the `continent` column.

In [30]:
#Write your code here
import pandas as pd

df = pd.read_csv('drinks.csv')
df['continent'] = df['continent'].replace({'AF': 'Africa', 'AS': 'Asia', 'EU': 'Europe', 'OC': 'Oceania', 'SA': 'South America'})

df.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

### Q8.5: Row max and min (4 marks)

Find out the country with the most and least `total_alcohol_consumption` and print:

"The country that consumes the most alcohol is: XXX."

"The country that consumes the least alcohol is: XXX."

In [31]:
#enter your answer here
import pandas as pd

df = pd.read_csv('drinks.csv')
df['total_alcohol_consumption'] = df['beer_servings'] + df['spirit_servings'] + df['wine_servings'] + df['total_litres_of_pure_alcohol']
most_consumption_country = df.loc[df['total_alcohol_consumption'].idxmax()]['country']
least_consumption_country = df.loc[df['total_alcohol_consumption'].idxmin()]['country']
print(f"The country that consumes the most alcohol is: {most_consumption_country}.")
print(f"The country that consumes the least alcohol is: {least_consumption_country}.")



The country that consumes the most alcohol is: Andorra.
The country that consumes the least alcohol is: Afghanistan.


### Q8.6: Calculation by group (5 marks)

calculate the following statistics for each continent:

Mean (average) of total_alcohol_consumption.  
Median (middle value) of total_alcohol_consumption.  
Maximum value of total_alcohol_consumption.  
Minimum value of total_alcohol_consumption.  
Number of unique countries in each continent.  

Store this data in a new pandas DataFrame named `continent_data`. The resulting `continent_data` DataFrame should have columns for `continent`, `mean_alcohol_consumption`, `median_alcohol_consumption`, `max_alcohol_consumption`, `min_alcohol_consumption`, and `unique_countries`.

In [32]:
#enter your answer here

import pandas as pd

df = pd.read_csv('drinks.csv')
df['total_alcohol_consumption'] = df['beer_servings'] + df['spirit_servings'] + df['wine_servings'] + df['total_litres_of_pure_alcohol']
continent_data = df.groupby('continent')['total_alcohol_consumption'].agg(['mean', 'median', 'max', 'min', 'nunique']).reset_index()
continent_data.columns = ['continent', 'mean_alcohol_consumption', 'median_alcohol_consumption', 'max_alcohol_consumption', 'min_alcohol_consumption', 'unique_countries']
print(continent_data)


  continent  mean_alcohol_consumption  median_alcohol_consumption  \
0        AF                 97.083019                       52.10   
1        AS                109.125000                       69.20   
2        EU                477.173333                      550.60   
3        OC                187.131250                      100.25   
4        SA                358.558333                      389.85   

   max_alcohol_consumption  min_alcohol_consumption  unique_countries  
0                    512.9                      0.0                49  
1                    657.5                      0.0                32  
2                    707.4                      0.0                44  
3                    555.4                      0.0                15  
4                    447.3                    219.8                12  


### Q8.7: Compare columns (3 marks)

Select all the countries that consume more beer than wine (i.e., `beer_servings` > `wine_servings`) , and store them in a list named `beer_lover`.

In [33]:
#enter your answer here
import pandas as pd

df = pd.read_csv('drinks.csv')
beer_lover = df.loc[df['beer_servings'] > df['wine_servings'], 'country'].tolist()
print(beer_lover)



['Albania', 'Algeria', 'Angola', 'Antigua & Barbuda', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia-Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', "Cote d'Ivoire", 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'China', 'Colombia', 'Congo', 'Costa Rica', 'Cuba', 'Cyprus', 'Czech Republic', 'DR Congo', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'Gabon', 'Gambia', 'Germany', 'Ghana', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iraq', 'Ireland', 'Israel', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kyrgyzstan', 'Latvia', 'Lesotho', 'Liberia', 'Lithuania', 'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Malta', 'Mauritius', 'Mexic

### 8.8 Identify minimum by group  (5 marks)

Find out the country that consumes the least alcohol (i.e., minimum of `total_alcohol_consumption`) in each continent. Then, for each continent, print the following statement: 

"The country that consumes the least alcohol inn {continent_name} is {country_name}"

In [34]:
#Write your code
import pandas as pd

df = pd.read_csv('drinks.csv')
df['total_alcohol_consumption'] = df['beer_servings'] + df['spirit_servings'] + df['wine_servings'] + df['total_litres_of_pure_alcohol']
min_alcohol_countries = df.loc[df.groupby('continent')['total_alcohol_consumption'].idxmin()][['continent', 'country']]
for index, row in min_alcohol_countries.iterrows():
    print(f"The country that consumes the least alcohol in {row['continent']} is {row['country']}.")


The country that consumes the least alcohol in AF is Libya.
The country that consumes the least alcohol in AS is Afghanistan.
The country that consumes the least alcohol in EU is Monaco.
The country that consumes the least alcohol in OC is Marshall Islands.
The country that consumes the least alcohol in SA is Bolivia.


### Q8.9 Compare multiple columns (6 marks)

Generate a new column `consume_most` in `df` which takes three values **"beer", "spirit" and "wine"** such that `consume_most` equals **"beer"** if a country consumes the most beer (i.e., `beer_servings` is larger than `wine_servings` and `spirit_servings`), `consume_most` equals **"spirit"** if a country consumes the most spirit, and `consume_most` equals **"wine"** if a country consumes the most wine.

**Note**: for countries consuming zero alcohol, do not assign a value to `consume_most`, i.e., `consume_most` takes a null value.

In [39]:
#enter your answer here

import pandas as pd

# Load the data into a DataFrame
df = pd.read_csv('drinks.csv')

# Generate the new column consume_most
conditions = [
    (df['beer_servings'] > df['spirit_servings']) & (df['beer_servings'] > df['wine_servings']),
    (df['spirit_servings'] > df['beer_servings']) & (df['spirit_servings'] > df['wine_servings']),
    (df['wine_servings'] > df['beer_servings']) & (df['wine_servings'] > df['spirit_servings'])
]
choices = ['beer', 'spirit', 'wine']

df['consume_most'] = np.select(conditions, choices, default=None)

# Print the updated DataFrame
print(df)


         country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent consume_most  
0                             0.0        AS         None  
1                             4.9        EU       spirit  
2                 

### THIS IS THE END OF THE TEST (100 marks available)

--------------