
# FBA - Python Exercise II

* This Exercise follow the same format as our final lab exam.
* Please enter your answers into the spaces provided.
* The expected outcome is presented below each space section as prompt (You won't have it in the exam!)
* In the lab exam, we recommend that you show comments in your code, to evidence your working if possible (comments may earn some credit even if your script code is not 100% correct).
* The exam will NOT mark on the elegance or efficiency of your coding, but rather getting the correct result in the instructed manner.
* This Exercise will cover all basic python practice we have done.

## Section 1 - Variables, Types & Operation

### Q1.1: Variable assignment

Create a variable `date_today` and assign a value to that variable that will represent today's date.

In [1]:
# Write your code here
date_today = 15

### Q1.2: Data Types & Operation 

In this question you have the following tasks:

* Assign to a variable `myint` the integer value of 6
* Assign to a variable `myfloat` the float value of 7.0
* Assign to a variable `mystring` the string value of '8.1'
* Assign to a variable `hello` to the string value of 'hello'
* Assign to a vairable `world` to the string value of 'world'
<br>

* Assign to a variable `sum_result` as the sum of `myint`, `myfloat` and `myfloat`
* Assign to a variable `helloworld` which combines the variables of `hello` and `world` and will be printed as `hello world`

* Print `sum_result` and `helloworld` to the console


In [89]:
# Write your code here

myint = 6
myfloat = 7.0
mystring = '8.1'
hello = 'hello'
world = 'world'

sum_result = myint + myfloat + float(mystring)
helloworld = hello + " " + world

print (sum_result)
print (helloworld)


21.1
hello world


## Section 2 - Loops & Conditionals

In the section, our goal is to construt the following pattern:


1<br>
22<br>
333<br>
4444<br>
55555<br>
666666<br>
7777777<br>
88888888<br>
999999999<br>

You will be asked to do this in several ways, using different python functions. Please complete these below:

### Q2.1: Use a for loop and the range() function

Use a for loop and range() function to construct the pattern above



In [3]:
# Write your code here
for i in range(10):
    print(str(i) * i)


1
22
333
4444
55555
666666
7777777
88888888
999999999


### Q2.2: Using a while loop - Option 1

Construct the pattern again using a while loop.

In [2]:
 # Write your code here
    
i = 1
while i < 10:
    print(str(i) * i)
    i += 1

1
22
333
4444
55555
666666
7777777
88888888
999999999


### Q2.3: Using a while loop - Option 2 

This time we want to use a `counter` and `while True` loop. You must exit the loop using  the `continue` or `break` statement (n.b. only one of these two commands will do what you want), and any other commands that you think useful.

In [4]:
 # Write your code here
counter = 1
while True:
    print(str(i) * i)
    counter += 1
    if counter >= 10:
        break

1
22
333
4444
55555
666666
7777777
88888888
999999999


# Section 3 - If statements

### Q3.1: Using if, elif and else
Define a function called `grade_converter` which takes a parameter `grade`. You need to use appropriate `if`, `elif` and `else` statements that will compare the input `grade` with a number and then return a letter grade:

* 90 or higher should get an "A"
* 80 - 89 should get a "B"
* 70 - 79 should get a "C"
* 65 - 69 should get a "D"
* Anything below a 65 should receive an "F"

Given a variable `mygrade` which takes an input as the grade of you, test your `grade_converter` function with the input.

In [7]:
# Write your code here

def grade_converter(grade):
    if grade >= 90:
        return "A"
    elif grade >= 80 and grade <= 89:
        return "B"
    elif grade >= 70 and grade <= 79:
        return "C"
    elif grade >= 65 and grade <= 69:
        return "D"
    else:
        return "F"

mygrade = int(input("Type your grade here: "))
print (grade_converter(mygrade))

Type your grade here: 100
A


### Q3.2: Nested conditionals 
Given an input variable `age` that takes the value of your age, please use <i>nested</i> if statements to cover the following cases:

- If the age is smaller than 18:
    - Print: 'You are Minor' and 'You are not Eligible to Work'
- If the number larger and equal to 18:
    - And if the age is smaller than and equal to 60, print: 'You are Eligible to Work' and 'Please fill in your details and apply'
    - And if the number larger than 60, print: 'You are too old to work as per the Government rules' and 'Please Collect your pension!'

In [6]:
# Write your code here
age = int(input(" Please Enter Your Age Here:  "))

if age < 18:
    print(" You are Minor ") 
    print(" You are not Eligible to Work ") 
else:
    if age <= 60:
        print(" You are Eligible to Work ")
        print(" Please fill in your details and apply")
    else:
        print(" You are too old to work as per the Government rules")
        print(" Please Collect your pension!")

 Please Enter Your Age Here:  18
 You are Eligible to Work 
 Please fill in your details and apply


### Q3.3: Error Checking by more Nesting
Add another if statement around your code in the previous question that checks that the supplied value in `age` is larger than 0. If it is, the code runs as before. If it isn't, print out the message "Invalid age input". (feel free to cut and paste your code from the previous question)

In [11]:
# Write your code here
age = int(input(" Please Enter Your Age Here:  "))

if age < 0:
    print (" Invalid age input ")
else:
    if age < 18:
        print(" You are Minor ") 
        print(" You are not Eligible to Work ") 
    else:
        if age <= 60:
            print(" You are Eligible to Work ")
            print(" Please fill in your details and apply")
        else:
            print(" You are too old to work as per the Government rules")
            print(" Please Collect your pension!")

 Please Enter Your Age Here:  -1
 Invalid age input 


# Section 4 - Data Structures

### Q4.1: List creation 

Create a list of animals that contains the following aminals: __'tiger', 'elephant', 'lion' and 'monkey'__ and assign it to a variable `zoo_list`. 

In [13]:
zoo_list = ['tiger', 'elephant', 'lion', 'monkey']

print(zoo_list)

['tiger', 'elephant', 'lion', 'monkey']


### Q4.2: List indexing and modification 

Update the `zoo_list` by replacing the `tiger` by `panda`. Add another two animals `penguin` and `hippo`.

In [14]:
zoo_list[zoo_list.index('tiger')] = 'panda'
zoo_list.append('penguin')
zoo_list.append('hippo')

print (zoo_list)

['panda', 'elephant', 'lion', 'monkey', 'penguin', 'hippo']


### Q4.3: List slicing

Create a list `middle` that contains only the two middle animals from `zoo_list`.

Create a list `last` that is made up only of the last two items from `zoo_list`.

In [73]:
# The middle two animals
middle = zoo_list[2:4]

# The last two items (index four and five)
last =  zoo_list[len(zoo_list)-2:len(zoo_list)]

# Print the two lists
print (middle)
print (last)

['lion', 'monkey']
['penguin', 'hippo']


### Q4.3: Insert new items in a list

Find the index of __"lion"__ and assign that result to a variable called `lion_index`.

Insert __"cobra"__ at that index (not replacing).

In [15]:
# Find the index of lion
lion_index = zoo_list.index("lion") # Use index() to find "lion"

# Insert the new animal
zoo_list.insert(lion_index, "cobra")

# Print the new zoo_list
print (zoo_list) 

['panda', 'elephant', 'cobra', 'lion', 'monkey', 'penguin', 'hippo']


### Q4.5: Dictionary creation

Create a dictionary `Prices` which contains the following pairs of grocery items and their prices:

|key|value|
|-|-|
|Cheese|8.4|
|Egg|2.9|
|Bread|1.8|
|Milk|2.4|
|Sausage|5.8|

Create another dictionary `Inventory` which contains the pairs of grocery items and their inventory levels.

|key|value|
|-|-|
|Cheese|16|
|Egg|87|
|Bread|30|
|Milk|18|
|Sausage|27|

For each key, print out the key along with its price and inventory information.

Print the answer in EXACTLY the following format:

<font color=grey>Cheese <br>
price: 8.4 <br>
inventory: 16 </font>

In [16]:
prices = {
    "Cheese" : 8.4,
    "Egg"  : 2.9,
    "Bread" : 1.8,
    "Milk"   : 2.4,
    "Sausage": 5.8
}

inventory = {
    "Cheese" : 16,
    "Egg"  : 87,
    "Bread" : 30,
    "Milk"   : 18,
    "Sausage": 27
}

for a in prices:
    print (a)
    print ("price: %s" % prices[a])
    print ("stock: %s" % inventory[a])
    print ()

Cheese
price: 8.4
stock: 16

Egg
price: 2.9
stock: 87

Bread
price: 1.8
stock: 30

Milk
price: 2.4
stock: 18

Sausage
price: 5.8
stock: 27



### Q4.6: Dictionary calculation 

Calculate how much money you would earn if you sell all the grocery items in stock.

For each key in `prices`, multiply the value in `prices` by the number in `inventory`. Sum the total value of all the inventory and print the `total`.

In [84]:
total = 0
for a in prices:
    total += prices[a] * inventory[a]

print (total)

640.5


### Q4.7: Calculation and updating a dictionary  

* Create a list called `shopping_list` that takes the values __"banana","orange", and "apple"__.

* Defined a function `bill` that takes a parameter `food`, which does the following tasks:

    - Calculate the costs of food as `total`. While looping through each item of food, the function should only add the price of the item to total if the item's inventory count is greater than zero. (You need to refer the price in the `prices` dictionary and the inventory level in the `inventory` dictionary).

    - If the item is in stock and after you add the price to the total, subtract one from the item's inventory count.

* Call the `bill` function to calculate the total costs of `shopping_list`.

* Print the updated `inventory`.

In [34]:
shopping_list = ["Cheese", "Milk", "Egg"]


def bill(food):
    total = 0
    for a in food:
        if inventory[a] > 0:
            total += prices[a]
            inventory[a] -= 1
    return total
  
print (bill(shopping_list))
print (inventory)



13.700000000000001
{'Cheese': 12, 'Egg': 74, 'Bread': 30, 'Milk': 14, 'Sausage': 27}


# Section 5 - Functions

### Q5.1: A basic function

Define a function `hello_world` that prints "Hello world!" to the console. You need to call the functon to test it.

In [32]:
# Write your code here
def hello_world():
  print ("Hello World!") #Prints 'Hello World!' to the console.

#Test your function here
hello_world()

Hello World!


### Q5.2: Function Parameters and calculation
Define a function `power` that takes two arguments: `base` and `exp`. This function should raise the `base` to the power of `exp`, and print the the sentence: `base` to the power of `exp` is `result`.

Call your function with a `base` of `18` and an `exp` of `5`. Your code should print: `18 to the power of 5 is 1889568.`

In [51]:
# Write your code here
def power(base,exponent):
  result = base ** exponent
  print ("%d to the power of %d is %d." % (base, exponent, result))

# call your function here
power(18,5)

18 to the power of 5 is 1889568.


### Q5.3: A function to sum values in a list
Define a function `sum_list` that sums all the values in a list.

Create a list `ls_test = [12, 14, 17, 19]` and test your function with this list.


In [3]:
# Write your code here
def sum_list(ls):
    total = 0
    for x in ls:
        total += x
    return total

# Test your function here
ls_test = [12, 14, 17, 19]
print(sum(ls_test))

62


# Section 6 - Module Import & Data Management

### Q6.1: Importing a module

Import the module `Numpy` with the usual shortcut name `np`

In [35]:
import numpy as np

### Q6.2: Ndarray Creation

Create a two-dimensional 4x3 matrix `mat` ranging from 1 to 12 using `NumPy array`.


In [40]:
# Write your code here
mat =  np.arange(1, 13).reshape(4,3)
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Q6.3: Mean

What is the mean of each row of the matrix `mat`? Please use a function in Numpy to do this (if needed, refer to the Numpy documentation to find the function to use and check its parameters).

In [41]:
for i in mat:
    print (np.mean(i))

2.0
5.0
8.0
11.0


### Q6.4: Array indices

Print out the indices of the maximum and minimum values in `mat`.

In [46]:
print("Maximum Values: ",np.argmax(mat))
print("Minimum Values: ",np.argmin(mat))

Maximum Values:  11
Minimum Values:  0


### Q6.5 Date format 

Create a new matrix `mat_f` which changes the datatype of `mat` to `float`.

In [47]:
# Write your code here
mat_f = mat.astype(float)

print(mat_f)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


# Section 7 - Reading a file manually

### Q7.1: Reading the first 10 lines

In the same folder as this Jupyter Notebook, you are given a file `Public_bike system_tripdata_201811.csv`.

* Using the standard Python functions (open(), read(), readline(), write(), ...), print the content of the first 10 lines of the file to the screen.

In [22]:
import csv
bike_csv = open('Public_bike system_tripdata_201811(3).csv')
bike= csv.reader(bike_csv, delimiter=',')

for row_num, row in enumerate(bike):
        if row_num <= 10:
            print (row)

['tripduration', 'starttime', 'stoptime', 'startstationid', 'startstationname', 'startstationlatitude', 'startstationlongitude', 'endstationid', 'endstationname', 'endstationlatitude', 'endstationlongitude', 'bikeid', 'usertype', 'birthyear', 'gender', 'random', 'insample']
['1498', '2018-11-09 08:50:39.1350', '2018-11-09 09:15:37.7090', '388', 'W 26 St & 10 Ave', '40.749718', '-74.002953', '327', 'Vesey Pl & River Terrace', '40.71534', '-74.016586', '31991', 'Subscriber', '1992', '1', '7.2279065e-08', '1']
['1004', '2018-11-03 14:47:50.2070', '2018-11-03 15:04:34.8700', '525', 'W 34 St & 11 Ave', '40.755943', '-74.002113', '530', '11 Ave & W 59 St', '40.771523', '-73.99054', '34396', 'Customer', '1969', '0', '1.1836472e-06', '1']
['242', '2018-11-02 00:39:07.3540', '2018-11-02 00:43:10.0260', '3169', 'Riverside Dr & W 82 St', '40.787209', '-73.981277', '3167', 'Amsterdam Ave & W 73 St', '40.779667', '-73.980934', '15203', 'Subscriber', '1966', '1', '2.0242212e-06', '1']
['673', '2018-

# Section 8 - Pandas


In this section, you are required to use Pandas to load the `Public_bike system_tripdata_201811(3).csv` file and explore it.

The `Public_bike system_tripdata_201811(3).csv` contains the data of a city's public bike sharing system for November 2018. The following items are inculded in the dataset:

* Trip Duration (seconds)
* Start Time and Date
* Stop Time and Date
* Start Station Name
* End Station Name
* Station ID
* Station Lat/Long
* Bike ID
* User Type (Customer = 24-hour pass or 3-day pass user; Subscriber = Annual Member)
* Gender (Zero=unknown; 1=male; 2=female)
* Year of Birth


### Q8.1: Loading data
<br>

Import the `Pandas` module as `pd`. <br>
<br>
Using one of Pandas functions, load `Public_bike system_tripdata_201811(3).csv` into a dataframe and assign it to a variable `df`.

In [9]:
# Write your code here
import pandas as pd
df = pd.read_csv('Public_bike system_tripdata_201811(3).csv')

### Q8.2: Displaying the first 10 lines
Display the first 10 lines of your dataframe

In [10]:
print (df.head(10))

   tripduration                 starttime                  stoptime  \
0          1498  2018-11-09 08:50:39.1350  2018-11-09 09:15:37.7090   
1          1004  2018-11-03 14:47:50.2070  2018-11-03 15:04:34.8700   
2           242  2018-11-02 00:39:07.3540  2018-11-02 00:43:10.0260   
3           673  2018-11-09 08:06:35.6140  2018-11-09 08:17:49.5970   
4           381  2018-11-05 15:12:51.8650  2018-11-05 15:19:13.7560   
5           818  2018-11-18 11:36:32.2060  2018-11-18 11:50:11.1740   
6           484  2018-11-04 08:40:57.9820  2018-11-04 08:49:02.5170   
7           873  2018-11-12 13:46:30.9890  2018-11-12 14:01:04.5500   
8           751  2018-11-14 13:29:28.5370  2018-11-14 13:42:00.4930   
9           806  2018-11-20 17:56:30.6730  2018-11-20 18:09:57.1060   

   startstationid          startstationname  startstationlatitude  \
0           388.0          W 26 St & 10 Ave             40.749718   
1           525.0          W 34 St & 11 Ave             40.755943   
2          

### Q8.3: Dataframe Shape

Display the shape of your dataframe

In [11]:
print (df.shape)

(40378, 17)


### Q8.4: Column Names 
Print out the column names of the data frame

In [12]:
print (df.columns)

Index(['tripduration', 'starttime', 'stoptime', 'startstationid',
       'startstationname', 'startstationlatitude', 'startstationlongitude',
       'endstationid', 'endstationname', 'endstationlatitude',
       'endstationlongitude', 'bikeid', 'usertype', 'birthyear', 'gender',
       'random', 'insample'],
      dtype='object')


### Q8.5: Transform date fromat

Transform `starttime` and `stoptime` from string into datetime format. <br>
You need to use the `to_datetime` function provided in pandas to complete this task.

In [13]:
# Write your code here
df['starttime'] = pd.to_datetime(df['starttime'])
df['stoptime'] = pd.to_datetime(df['stoptime'])

### Q8.6: Extracting time elements and create new column

Create new columns in `df`: `Month`, `Week`,`Day`, `Hour`. You can extract them from either `starttime` or `stoptime`.

In [14]:
# Write your code here
df['Month'],df['Week'],df['Day'],df['Hour'] = df['starttime'].dt.month,df['starttime'].dt.week,df['starttime'].dt.day,df['starttime'].dt.hour


### Q8.7: Extract multiple columns
Print on the screen the newly created columns: `Month`, `Week`,`Day`, `Hour`.

In [15]:
# Write your code here
print(df[['Month', 'Week', 'Day', 'Hour']])

       Month  Week  Day  Hour
0         11    45    9     8
1         11    44    3    14
2         11    44    2     0
3         11    45    9     8
4         11    45    5    15
5         11    46   18    11
6         11    44    4     8
7         11    46   12    13
8         11    46   14    13
9         11    47   20    17
10        11    48   26    13
11        11    44    4     9
12        11    46   17    12
13        11    46   13    22
14        11    44    2    17
15        11    48   28    21
16        11    44    4    20
17        11    44    3    16
18        11    46   17     9
19        11    45    7    18
20        11    44    4    16
21        11    44    4    20
22        11    46   16    13
23        11    45    8    16
24        11    45   10    17
25        11    46   12    12
26        11    46   15    15
27        11    44    4    22
28        11    46   14    13
29        11    46   18     2
...      ...   ...  ...   ...
40348     11    46   18    13
40349     

### Q8.8: Data summary

Print the number of bike usage in the first and last day of November.

In [16]:
Firstday = df[df.Day == 1]
Lastday = df[df.Day == 30]
print('The public bikes were used for ',len(Firstday),' times in the first day of November')
print('The public bikes were used for ',len(Lastday),' times in the last day of November')

The public bikes were used for  2432  times in the first day of November
The public bikes were used for  1465  times in the last day of November


### Q8.9: Row filtering 

Extract the rows where the `tripduration` is larger than 10000 as `long_trip`

In [17]:
long_trip = df[df.tripduration > 10000]
print(long_trip)

       tripduration               starttime                stoptime  \
485           26518 2018-11-02 10:20:15.751 2018-11-02 17:42:14.381   
1744          13881 2018-11-26 09:02:56.229 2018-11-26 12:54:17.651   
1749          60888 2018-11-16 19:14:26.421 2018-11-17 12:09:15.057   
1779          23510 2018-11-30 12:35:33.828 2018-11-30 19:07:24.378   
3543         503902 2018-11-11 18:55:21.536 2018-11-17 14:53:44.103   
4103          22265 2018-11-05 08:01:49.945 2018-11-05 14:12:54.969   
4416          14662 2018-11-01 10:33:51.011 2018-11-01 14:38:13.864   
5594          11893 2018-11-02 03:09:25.839 2018-11-02 06:27:39.535   
5768          17902 2018-11-04 06:33:00.019 2018-11-04 11:31:22.538   
5899          14965 2018-11-23 17:19:59.567 2018-11-23 21:29:24.869   
5909          49404 2018-11-06 19:14:59.398 2018-11-07 08:58:23.491   
5958          86878 2018-11-10 15:39:37.758 2018-11-11 15:47:35.770   
6394          39339 2018-11-22 11:57:04.829 2018-11-22 22:52:44.499   
6993  

### Q8.10:  Sort dataframe

Select top 50 most popular stations (including both start station and end station)


In [19]:
# Filter stations
top_50_stations = (df['startstationid'].value_counts() + df['endstationid'].value_counts()).sort_values(ascending=False).head(50)
print (top_50_stations)


519.0     678.0
435.0     576.0
497.0     560.0
402.0     533.0
285.0     490.0
490.0     482.0
499.0     461.0
3255.0    448.0
477.0     422.0
459.0     419.0
491.0     415.0
293.0     412.0
445.0     401.0
3660.0    400.0
468.0     399.0
229.0     396.0
359.0     394.0
382.0     382.0
379.0     379.0
3435.0    374.0
3164.0    373.0
3641.0    367.0
281.0     363.0
523.0     358.0
151.0     358.0
3263.0    353.0
505.0     351.0
368.0     350.0
358.0     340.0
3711.0    334.0
3687.0    331.0
426.0     330.0
517.0     328.0
465.0     327.0
486.0     315.0
127.0     312.0
442.0     308.0
168.0     304.0
446.0     298.0
173.0     297.0
509.0     295.0
3427.0    295.0
466.0     294.0
504.0     293.0
483.0     292.0
507.0     291.0
514.0     286.0
545.0     284.0
479.0     281.0
472.0     277.0
dtype: float64


### Q8.11:  Identify business problem
For a bike share system, one of the issue is to make sure that there are bikes available at stations where people want to pick them up. 

If station $A$ starts the day with lots of bikes, but people take them out to other stations and nobody returns any bikes to $A$, then it will run out of bikes, and that's the thing we don't want. 

Your task is to think about the transition of bikes between stations and locate which stations would be more likely to suffer bike __outage__ or __overage__:

* locate top 5 stations which are most likely to suffer daily bike outage (if any).

* locate top 5 stations which are most likely to have daily bike overage (if any). 

In [20]:
# Find outage stations and list your result
top_5_outrage = (df['endstationid'].value_counts() - df['startstationid'].value_counts()).sort_values().head(5)
print(top_5_outrage)

3159.0   -37.0
358.0    -36.0
517.0    -30.0
307.0    -29.0
403.0    -29.0
dtype: float64


In [21]:
# Find overage stations and list your result
top_5_overrage = (df['endstationid'].value_counts() - df['startstationid'].value_counts()).sort_values(ascending=False).head(5)
print(top_5_overrage)

324.0    58.0
491.0    39.0
466.0    36.0
497.0    34.0
503.0    33.0
dtype: float64


## THIS IS THE END OF THE EXERCISE

--------------