In [91]:
numpy

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
# 创建矩阵
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
type(a) #<class 'numpy.ndarray'>

np.append(a,[[1,2],[1,2]],axis=0) # 添加整行元素
np.append(a,[[1,2],[1,2]],axis=1) # 添加整列

# 矩阵结构
a.shape #(3, 3)

a.T # T（变换矩阵）
len(a) # 3
np.mean(a) # 5.0
np.var(a) # 方差
np.std(a),axis=0 # 标准差 # axis：0每行，1每列
np.sqrt(a) # 开平方
np.min(a) #1
np.max(a) #9
np.dot(a,b) # dot(形状不同的矩阵相乘)

# 转换形式为float
print(a.astype("float"))

# 1 2行 3个
b = np.ones((2,3))
# 0 2*2矩阵
c = np.zeros((2,2))
# 用7形成2*2矩阵
d= np.full((2,2),7)
# 对角线1
f = np.eye(3)

# 切片
# [行的切片,列的切片]
# [行的起始位置:行的结束位置:步长,列的起始位置:列的结束位置:步长]
a[:,1]
a[1,:]
a[1:3:1,1:3:1]

#随机数生成3*4矩阵
g = np.random.randint(1,100,size=[3,4])

# 创建形状相同矩阵
y = np.empty_like(a)

# 布尔值 或用｜，和用＆
bool_idx = (a<2) & (a>4)


In [115]:
pandas Series

k1    v1
k2    v2
k3    v3
dtype: object

In [111]:
import pandas as pd

data = pd.read_csv("文件名") # 读写文件
data.head(5) # 显示前五行
df.tail(5) # 显示后五行
df.describe() # 显示7个特征

# Series行名index和values
s1 = pd.Series([1,2,3]) # values
s2 = pd.Series({'k1':'v1','k2':'v2','k3':'v3'}) 
s3 = pd.Series(['a','b','c','d'],index=['10','20','30','40'])

s2.T # 转换
s2.index # 查看行名
s2.values # 查看数据

In [114]:
pandas DataFrame

name  age gender
0   张三   20      男
1   李四   21      女
2   王二   22      男

In [94]:
# DataFrame  传入一个字典
df = pd.DataFrame({"name":["张三","李四","王二"],"age":[20,21,22],"gender":["男","女","男"]})
df.index # 查看行名
df.columns # 查看列名
df.values # 查看数据
df[['name','age']] #查看固定列
df['列索引名']['行索引名'] #查看固定列固定行
df.reset_index('Loan_ID') #重置索引

# 截取iloc[row_index, column_index]
df.iloc[1] #第1行，全部列 
df.iloc[:,1:2] #全部行，第一列
df.iloc[[1,2,3],[0,2]] #取123行，02列

#筛选
df[df.A > 0] # A列中比0大的
df[df['E'].isin(['two','four'])] # E列中为two和four的

#替换值
df2.replace({'a':{'Y':'Yes','N':'No'}}) #将a列的Y替换为Yes，N替换为No

# 插入新列
df['a'] = [1,2,3]  # 插入值为[1,2,3]的a列
df['d'] = df['a'] + df['age'] #插入d列，值为a和age之和

# 用numpy 来构造一个 DataFrame
df = pd.DataFrame(np.random.randn(5,5)（随机5*5矩阵）,index =np.arange(5),columns=list('abcde'))
df = pd.DataFrame(np.random.randint(1,100,size=[5,5]),index =np.arange(5),columns=list('abcde'))

# 排序 默认升序
df.sort_values(by = ['a','b'],ascending =False)# 规定按照降序排序
# 以列(行)为基准
df.sort_index(axis=0(axis=1),ascending = False)
              
#NaN值
df.isnull() #查看缺失值，返回布尔值
df.isnull().any() #返回列名
df.isnull().sum() #查缺失个数
df.dropna() #删除缺失
print(d.dropna(axis=0)) # axis：0列，1行
df.fillna(df.mean( ))# 用平均值填充NaN
df.median( ) # 中位数
df.mode() # 众数
df.value_counts( ) #算出现个数

# 保存
df.to_csv